name: jupyterlab-ros
channels:
- conda-forge
- robostack
- khalilahmed724/label/khalilahmed724
dependencies:
- python=3.8
- nodejs=14
- jupyterlab=3.1
- ipympl
- ipyvuetify
- bqplot
- ipywidgets
- voila
- ros-noetic-ros-core
- ros-neotic-myrobo
- ros-noetic-robm
# our stuff
- robostack::jupyterlab-ros
- robostack::jupyter-amphion
# - robostack::jupyter-ros=0.5
